# Generated by Django 5.2 on 2025-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
