# Generated by Django 5.2 on 2025-06-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicenet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghluser',
            old_name='calander_id',
            new_name='calendar_id',
        ),
    ]
