# Generated by Django 5.2 on 2025-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenet', '0002_rename_calander_id_ghluser_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghluser',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
