# Generated by Django 5.2 on 2025-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenet', '0004_ghluser_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_appointment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ghl_task_id', models.CharField(max_length=100, unique=True)),
                ('contact_id', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
